language: go

go:
        - 1.3
        - 1.4
        - 1.5
        - tip

env:
        - GIMME_OS=linux GIMME_ARCH=amd64

install:
        - go get github.com/tools/godep
        - godep restore

script:
        - test -z "$(go fmt ./...)"
        - test -z "$(go vet ./...)"
        - go test .
