language: go

os:
        - linux

go:
        - 1.5
        - tip

before_install:
        - go get github.com/axw/gocov/gocov
        - go get github.com/mattn/goveralls
        - if ! go get github.com/golang/tools/tree/master/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
        - go get github.com/golang/lint/golint
        - go get github.com/jgautheron/goconst/cmd/goconst
        - go get github.com/mdempsky/unconvert

script:
        - $HOME/gopath/bin/goveralls
        - test -z "$(go fmt ./...)"
        - test -z "$(go vet ./...)"
        - test -z "$(golint)"
        - test -z "$(goconst .)"
        - test -z "$(unconvert -v .)"
        - go test -test.v .
